### ISSUE TITLE
How to run as dev

### ISSUE THREAD

**Issue by theprobugmaker** [andrewthauer/ts-monorepo#5]
I noticed that you only have scripts to run build but what about dev like `ts-node-dev` or `nodemon`?

**Comment by andrewthauer** [comment]
It's been a while since I originally set this POC up. However, I would guess that adding an npm script that runs `tsc --watch` in each project via `lerna run` might do the trick.

This might also be relevant if upgrading to TS 3.8+ https://www.typescriptlang.org/docs/handbook/configuring-watch.html.

**Comment by theprobugmaker** [comment]
Thank you very much. I asked this cause I saw a few repo repositories using paths only but I saw that it has a problem with that if you work with similar files and directories in both packages as it will always include the file from the package requiring the other one.
Using references I would need to build every time I have a new modification right? That is why I thought about using paths.
What is your recommendation, going with paths and forgetting about references or keep references as it has something I don't know about? (I'm not going to be publishing any repository it's all for the same project)
